<!DOCTYPE html>
<html>
<head>
    <title><?= $title ?></title>
    <?php include '_css.phtml' ?>
    <link rel="stylesheet" href="css/app.css" >
</head>
<body class="my-login-page">
<section class="h-100">
    <div class="container h-100">
        <div class="row justify-content-md-center h-100">
            <div class="card-wrapper">
                <div class="brand">
                    <img src="img/logo.png">
                </div>
                <div class="card fat">
                    <div class="card-body">
                        <h4 class="card-title text-center"><?= $title ?></h4>
                        <?php if(!empty($data['error'])): ?>
                            <p class="card-text text-danger"><?=$data['error']?></p>
                        <?php endif ?>
                        <?=$content?>
                    </div>
                </div>
                <div class="footer text-muted">
                    <small>Copyright &copy; Plena Data 2018</small>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
<?php include '_js.phtml' ?>
</html>