<?php $title = 'Account Recovery'?>
<?php ob_start() ?>
    <?php if(!empty($sentTo)): ?>
        <p>
            Reset password link was sent to <?= $sentTo ?>,
            please check your email and follow the instructions.
        </p>
    <?php else: ?>
        <form method="POST">

            <div class="form-group">
                <label for="email">E-Mail Address</label>
                <input id="email" type="email" class="form-control" name="email" value="" required autofocus>
                <div class="form-text text-muted">
                    By clicking "Reset Password" we will send a password reset link
                </div>
            </div>

            <div class="form-group no-margin">
                <button type="submit" class="btn btn-primary btn-block">
                    Reset Password
                </button>
            </div>
        </form>
    <?php endif ?>
<?php $content = ob_get_clean() ?>
<?php include '_account_layout.phtml' ?>