<?php $title = 'Login'?>
<?php ob_start() ?>
    <form method="POST">
        <div class="form-group">
            <label for="email">User Name</label>

            <input id="username" type="text" class="form-control"
                   name="username" value="" tabindex="1" required autofocus>
        </div>
        <div class="form-group">
            <label for="password">Password</label>

            <input id="password" type="password" class="form-control"
                   name="password" tabindex="2" required data-eye>

        </div>
        <div class="form-group no-margin">
            <button type="submit" class="btn btn-primary btn-block">
                Login
            </button>
        </div>
        <div class="margin-top20 text-center">
            <a href="/forgot" class="float-left">
                Forgot Password?
            </a>
            <a class="float-right" href="/register">Register</a>
        </div>
    </form>
<?php $content = ob_get_clean() ?>
<?php include '_account_layout.phtml' ?>