<?php $title = 'Register'?>
<?php ob_start() ?>
    <form method="POST">

        <div class="form-group">
            <label for="username">Name</label>
            <input id="username" type="text" class="form-control" name="username" required autofocus>
        </div>

        <div class="form-group">
            <label for="email">E-Mail Address</label>
            <input id="email" type="email" class="form-control" name="email" required>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input id="password" type="password" class="form-control" name="password" required >
        </div>

        <div class="form-group">
            <label for="password2">Verify Password</label>
            <input id="password2" type="password" class="form-control" name="password2" required >
        </div>

        <div class="form-group no-margin">
            <button type="submit" class="btn btn-primary btn-block">
                Register
            </button>
        </div>
        <div class="margin-top20 text-center">
            Already have an account? <a href="/login">Login</a>
        </div>
    </form>
<?php $content = ob_get_clean() ?>
<?php include '_account_layout.phtml' ?>
