<?php $title = 'Reset Password'?>
<?php ob_start() ?>
    <form method="POST">
        <fieldset <?= $data['disabled'] ? 'disabled' : ''?> >
            <input type="hidden" name="auth" value="<?= $auth ?>">

            <div class="form-group">
                <label for="new-password">New Password</label>
                <input id="new-password" type="password" class="form-control" name="password"
                       required autofocus >
            </div>
            <div class="form-group">
                <label for="new-password">Verify New Password</label>
                <input id="new-password2" type="password" class="form-control" name="password2"
                       required >
            </div>

            <div class="form-group no-margin">
                <button type="submit" class="btn btn-primary btn-block">
                    Reset Password
                </button>
            </div>
        </fieldset>
    </form>
<?php $content = ob_get_clean() ?>
<?php include '_account_layout.phtml' ?>